language: cpp
dist: xenial

git:
  depth: 10

os: linux
compiler: gcc           # g++-5, Qt5.12.0, MONOLITHIC_BUILD
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
    packages: 
      - gcc-7
      - g++-7
      - libstdc++-6-dev
      - qt512base
      - qt512declarative
env: COMPILER=g++-7 QT=512 DISABLE_IPC=OFF MONOLITHIC_BUILD=ON

before_install:
  - sudo apt-get install -y gcc-7
  - export CC=/usr/bin/gcc-7
install:
- sudo apt-get install python3 python3-pip python3-setuptools graphviz doxygen libgl1-mesa-dev qtdeclarative5-private-dev python3-click python3-path python3-pip python3-jinja2 python3-yaml cmake qtdeclarative5-dev qml-module-qtquick-controls qtdeclarative5-private-dev libgtest-dev libpthread-stubs0-dev
#- sudo add-apt-repository ppa:jonathonf/gcc-7.3 -y
#- sudo apt-get update
#- sudo apt-get install gcc-7 g++-7
#- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
- sudo pip3 install antlr4-python3-runtime six pyyaml click typing jinja2 watchdog path.py
- sudo apt purge --auto-remove cmake && sudo apt install snapd && sudo snap install cmake --classic

before_script:
- QTDIR="/opt/qt${QT}"
- PATH="$QTDIR/bin:$PATH"
- source /opt/qt${QT}/bin/qt${QT}-env.sh
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- source setup_gtest.sh

script:
- export CC=gcc-7
- export CXX=g++-7
- cd build
- >
  cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=Release -DFACELIFT_DISABLE_DBUS_IPC=${DISABLE_IPC} -DENABLE_MONOLITHIC_BUILD=${MONOLITHIC_BUILD} -DFACELIFT_BUILD_TESTS=ON -DCMAKE_SYSTEM_PREFIX_PATH=$CMAKE_SYSTEM_PREFIX_PATH ..
- make -j2 && dbus-launch make check && cat ./tests/results.csv
#- cat ${COMPILER}
#- cat ${DISABLE_IPC}
#- cat ${MONOLITHIC_BUILD}
#- cat ${CMAKE_SYSTEM_PREFIX_PATH}
#- cat $CMAKE_SYSTEM_PREFIX_PATH
#- cat /home/travis/build/kunichik/facelift/build/CMakeFiles/CMakeOutput.log
#- cat /home/travis/build/kunichik/facelift/build/CMakeFiles/CMakeError.log
